### ISSUE TITLE
Rubyのバージョンを2.4にする

### ISSUE THREAD

**Issue by hidetomasuoka** [manma-co/matching-system#1]
2.3ではログローテーションのバグがあるので2．4で開発する

https://bugs.ruby-lang.org/issues/12948

**Comment by yoshi522** [comment]
開発環境のrubyのバージョンをアップデートしました。

一応READMEも。
https://github.com/manma-co/matching-system/commit/3d34cfbc545653d9395ebc0c8e3429e3a7258f30
